<?php
// lang.php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Handle language selection via GET parameter
if (isset($_GET['lang'])) {
    $reqLang = strtolower(trim($_GET['lang']));
    if (in_array($reqLang, ['id', 'en'], true)) {
        $_SESSION['lang'] = $reqLang;
        setcookie('app_lang', $reqLang, time() + (86400 * 365), '/');
    }
}

// Determine active language
$currentLang = $_SESSION['lang'] ?? $_COOKIE['app_lang'] ?? 'id';
if (!in_array($currentLang, ['id', 'en'], true)) {
    $currentLang = 'id';
}

$translations = [
    'id' => [
        // Brand & Header
        'brand_title' => 's.pknstan.id',
        'brand_badge' => 'Link Shortener',
        'linktree_nav' => 'Linktree',
        'logout' => 'Keluar',
        'theme_toggle' => 'Ganti tema terang atau gelap',
        'language' => 'Bahasa',

        // Login View
        'login_title' => 'Login Administrator',
        'login_desc' => 'Masuk untuk membuat, mengelola, dan melacak tautan pendek.',
        'username' => 'Username',
        'username_placeholder' => 'Masukkan username administrator',
        'password' => 'Password',
        'password_placeholder' => 'Masukkan password',
        'sign_in' => 'Masuk',
        'login_error' => 'Username atau password salah. Silakan coba lagi.',

        // Shortener View
        'create_title' => 'Buat Tautan Pendek',
        'create_desc' => 'Hasilkan tautan ringkas, judul, dan kode QR untuk URL apa pun.',
        'dest_url' => 'URL Tujuan',
        'dest_placeholder' => 'https://example.com/jalur-panjang',
        'title_desc' => 'Judul / Deskripsi',
        'title_placeholder' => 'Contoh: Panduan Pendaftaran STAN 2026',
        'custom_alias' => 'Alias Kustom (Opsional)',
        'custom_alias_placeholder' => 'Contoh: stan-reg',
        'short_alias' => 'Alias Pendek',
        'shorten_btn' => 'Pendekkan Tautan',
        'shortening' => 'Memproses...',
        'link_created' => 'Tautan berhasil dibuat',
        'copy' => 'Salin',
        'copied' => 'Disalin!',
        'qr_code' => 'QR Code',
        'download_qr' => 'Unduh QR (PNG)',
        'download_qr_btn' => 'Unduh Gambar QR',
        'download_png' => 'Unduh PNG',
        'recent_links' => 'Daftar Tautan Terbaru',
        'empty_links' => 'Belum ada tautan pendek',
        'empty_links_desc' => 'Masukkan URL tujuan di atas untuk membuat tautan dan kode QR pertama Anda.',
        'col_short' => 'Tautan Pendek',
        'col_title_dest' => 'Judul & Tujuan',
        'col_clicks' => 'Klik',
        'col_date' => 'Tanggal Dibuat',
        'col_actions' => 'Aksi',
        'edit' => 'Edit',
        'delete' => 'Hapus',
        'save_changes' => 'Simpan Perubahan',
        'cancel' => 'Batal',
        'edit_link_title' => 'Edit Tautan Pendek',
        'confirm_delete' => 'Apakah Anda yakin ingin menghapus tautan ini?',
        'link_updated' => 'Tautan berhasil diperbarui.',
        'invalid_data_edit' => 'Data edit tidak valid. Judul, kode pendek, dan URL tujuan wajib diisi.',
        'code_in_use' => 'Kode pendek "/{code}" sudah digunakan oleh tautan lain.',
        'db_error' => 'Terjadi kesalahan database saat menyimpan perubahan.',

        // Dashboard Linktree Banner
        'tree_banner_title' => 'Halaman Bio Link (Multi-Tree)',
        'tree_banner_desc' => 'Kelola {count} halaman profil tautan dengan URL kustom masing-masing untuk media sosial.',
        'manage_all_trees' => 'Kelola Semua Tree',

        // Tree Page Admin
        'admin_mode' => 'Admin Multi-Tree',
        'admin_mode_title' => 'Pengelola Multi-Tree',
        'admin_mode_desc' => 'Buat beberapa halaman bio link dengan URL kustom masing-masing untuk unit, kegiatan, atau organisasi.',
        'managing_tree_label' => 'Mengelola Tree:',
        'select_tree' => 'Pilih Tree:',
        'create_new_tree' => '+ Buat Tree Baru',
        'manage_this_tree' => 'Kelola Tree Ini',
        'all_trees' => 'Semua Tree',
        'view_public' => 'Lihat Publik',
        'shortener_nav' => 'Shortener',
        'copy_url' => 'Salin URL',
        'add_link_to_tree' => 'Tambah Tautan ke Tree Ini',
        'add_link_desc' => 'Tambahkan tautan kustom atau pilih langsung dari shortlink yang ada.',
        'quick_import_label' => 'Pilih dari Shortlink Tersedia (Opsional)',
        'quick_import_placeholder' => '-- Ketik manual atau pilih shortlink --',
        'link_title' => 'Judul Tautan',
        'link_title_placeholder' => 'Contoh: Pengumuman Seleksi PMB',
        'link_sub' => 'Keterangan Singkat (Opsional)',
        'link_sub_placeholder' => 'Contoh: Dokumen pdf panduan resmi',
        'link_url' => 'URL Tujuan',
        'icon_choice' => 'Pilihan Ikon',
        'icon_link' => 'Tautan Umum',
        'icon_globe' => 'Website Resmi',
        'icon_document' => 'Dokumen / PDF',
        'icon_calendar' => 'Jadwal / Agenda',
        'icon_megaphone' => 'Pengumuman',
        'icon_chat' => 'Grup / Kontak',
        'icon_star' => 'Tautan Utama',
        'badge_label' => 'Label / Badge',
        'badge_placeholder' => 'Contoh: Baru / Penting',
        'add_to_tree_btn' => 'Tambah ke Tree Ini',
        'tree_slug_profile' => 'Kustomisasi URL Slug & Profil',
        'tree_slug_desc' => 'Ubah URL slug akses publik dan informasi identitas tree ini.',
        'custom_slug' => 'Custom URL Slug',
        'slug_help' => 'Hanya huruf, angka, strip (-), atau garis bawah (_).',
        'tree_title' => 'Judul Tree',
        'tree_bio' => 'Bio / Keterangan Resmi',
        'website_url' => 'Website Resmi URL',
        'instagram_url' => 'Instagram URL',
        'youtube_url' => 'YouTube URL',
        'telegram_url' => 'Telegram URL',
        'save_tree_btn' => 'Simpan Pengaturan & URL Slug',
        'delete_tree_btn' => 'Hapus Tree',
        'delete_tree_confirm' => 'Yakin ingin menghapus tree ini beserta semua tautan di dalamnya?',
        'links_in_tree' => 'Daftar Tautan di Tree Ini',
        'empty_tree_links' => 'Belum ada tautan di tree ini',
        'empty_tree_links_desc' => 'Gunakan form di sebelah kiri untuk menambahkan tautan pertama ke tree ini.',
        'active_status' => 'Aktif',
        'inactive_status' => 'Off',
        'inactive_label' => '(Nonaktif)',
        'clicks_count' => '{count} klik',
        'total_links_count' => '{count} tautan',
        'total_clicks_count' => '{count} total klik',
        'create_tree_title' => 'Buat Tree Baru',
        'create_tree_desc' => 'Tentukan URL kustom (slug) dan identitas tree baru Anda.',
        'create_tree_btn' => 'Buat Tree Baru',
        'available_trees' => 'Daftar Tree yang Tersedia',
        'manage_links' => 'Kelola Link',
        'see' => 'Lihat',
        'edit_tree_link_title' => 'Edit Tautan Linktree',
        'tree_not_found' => 'Tree Tautan Tidak Ditemukan',
        'tree_not_found_desc' => 'Halaman bio link dengan URL yang Anda minta tidak tersedia atau telah dipindahkan.',
        'go_home' => 'Kembali ke Beranda',
        'share' => 'Bagikan',
        'scan_qr_desc' => 'Pindai kode di atas menggunakan kamera ponsel untuk membuka halaman bio link ini secara instan.',
        'close' => 'Tutup',
        'url_copied_toast' => 'URL Linktree berhasil disalin!',
        'no_active_links' => 'Belum ada tautan aktif di tree ini',
        'check_back_later' => 'Silakan periksa kembali beberapa saat lagi.',
        'qr_code_title' => 'QR Code Linktree',
        'footer_text' => '© ' . date('Y') . ' MYP',

        // Reorganized Management UI Tabs & Keys
        'tab_links' => 'Tautan',
        'tab_profile' => 'Profil & Pengaturan',
        'tab_all_trees' => 'Semua Tree',
        'btn_add_link' => '+ Tambah Tautan Baru',
        'btn_hide_form' => 'Tutup Form',
        'danger_zone' => 'Zona Bahaya',
        'danger_zone_desc' => 'Hapus tree ini secara permanen beserta seluruh tautan di dalamnya.',
        'stats_active_links' => '{count} tautan aktif',
        'stats_total_clicks' => '{count} total klik',
        'btn_back_to_shortener' => 'Shortener',
        'empty_tree_cta' => 'Tambah Tautan Pertama',
        'move_up' => 'Naikkan urutan',
        'move_down' => 'Turunkan urutan',
        'social_section_title' => 'Tautan Media Sosial & Eksternal',
        'identity_section_title' => 'Identitas & URL Slug',
    ],
    'en' => [
        // Brand & Header
        'brand_title' => 's.pknstan.id',
        'brand_badge' => 'Link Shortener',
        'linktree_nav' => 'Linktree',
        'logout' => 'Logout',
        'theme_toggle' => 'Toggle light or dark theme',
        'language' => 'Language',

        // Login View
        'login_title' => 'Administrator Login',
        'login_desc' => 'Sign in to create, manage, and track shortened links.',
        'username' => 'Username',
        'username_placeholder' => 'Enter administrator username',
        'password' => 'Password',
        'password_placeholder' => 'Enter password',
        'sign_in' => 'Sign In',
        'login_error' => 'Incorrect username or password. Please try again.',

        // Shortener View
        'create_title' => 'Create Short Link',
        'create_desc' => 'Generate a concise link, title, and QR code for any URL.',
        'dest_url' => 'Destination URL',
        'dest_placeholder' => 'https://example.com/very-long-path',
        'title_desc' => 'Title / Description',
        'title_placeholder' => 'e.g. STAN 2026 Registration Guide',
        'custom_alias' => 'Custom Alias (Optional)',
        'custom_alias_placeholder' => 'e.g. stan-reg',
        'short_alias' => 'Short Alias',
        'shorten_btn' => 'Shorten Link',
        'shortening' => 'Processing...',
        'link_created' => 'Link created successfully',
        'copy' => 'Copy',
        'copied' => 'Copied!',
        'qr_code' => 'QR Code',
        'download_qr' => 'Download QR (PNG)',
        'download_qr_btn' => 'Download QR Image',
        'download_png' => 'Download PNG',
        'recent_links' => 'Recent Links',
        'empty_links' => 'No shortened links yet',
        'empty_links_desc' => 'Enter a destination URL above to generate your first link and QR code.',
        'col_short' => 'Short Link',
        'col_title_dest' => 'Title & Destination',
        'col_clicks' => 'Clicks',
        'col_date' => 'Created Date',
        'col_actions' => 'Actions',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save_changes' => 'Save Changes',
        'cancel' => 'Cancel',
        'edit_link_title' => 'Edit Short Link',
        'confirm_delete' => 'Are you sure you want to delete this link?',
        'link_updated' => 'Link updated successfully.',
        'invalid_data_edit' => 'Invalid data provided for link edit. Title, short code, and destination URL are required.',
        'code_in_use' => 'The short code "/{code}" is already in use by another link.',
        'db_error' => 'Database error while saving changes.',

        // Dashboard Linktree Banner
        'tree_banner_title' => 'Bio Link Pages (Multi-Tree)',
        'tree_banner_desc' => 'Manage {count} bio link profile pages with custom URLs for social media.',
        'manage_all_trees' => 'Manage All Trees',

        // Tree Page Admin
        'admin_mode' => 'Multi-Tree Admin',
        'admin_mode_title' => 'Multi-Tree Manager',
        'admin_mode_desc' => 'Create multiple bio link pages with custom URLs for units, events, or organizations.',
        'managing_tree_label' => 'Managing Tree:',
        'select_tree' => 'Select Tree:',
        'create_new_tree' => '+ Create New Tree',
        'manage_this_tree' => 'Manage This Tree',
        'all_trees' => 'All Trees',
        'view_public' => 'View Public',
        'shortener_nav' => 'Shortener',
        'copy_url' => 'Copy URL',
        'add_link_to_tree' => 'Add Link to This Tree',
        'add_link_desc' => 'Add custom links or select directly from existing shortened links.',
        'quick_import_label' => 'Select from Available Shortlinks (Optional)',
        'quick_import_placeholder' => '-- Type manually or select shortlink --',
        'link_title' => 'Link Title',
        'link_title_placeholder' => 'e.g. 2026 Admissions Portal',
        'link_sub' => 'Short Subtitle (Optional)',
        'link_sub_placeholder' => 'e.g. Official PDF guide document',
        'link_url' => 'Destination URL',
        'icon_choice' => 'Icon Choice',
        'icon_link' => 'General Link',
        'icon_globe' => 'Official Website',
        'icon_document' => 'Document / PDF',
        'icon_calendar' => 'Schedule / Calendar',
        'icon_megaphone' => 'Announcement',
        'icon_chat' => 'Group / Contact',
        'icon_star' => 'Featured Link',
        'badge_label' => 'Label / Badge',
        'badge_placeholder' => 'e.g. New / Important',
        'add_to_tree_btn' => 'Add to This Tree',
        'tree_slug_profile' => 'Customize URL Slug & Profile',
        'tree_slug_desc' => 'Change the public access slug URL and identity information for this tree.',
        'custom_slug' => 'Custom URL Slug',
        'slug_help' => 'Letters, numbers, dashes (-), or underscores (_) only.',
        'tree_title' => 'Tree Title',
        'tree_bio' => 'Bio / Official Description',
        'website_url' => 'Official Website URL',
        'instagram_url' => 'Instagram URL',
        'youtube_url' => 'YouTube URL',
        'telegram_url' => 'Telegram URL',
        'save_tree_btn' => 'Save Settings & URL Slug',
        'delete_tree_btn' => 'Delete Tree',
        'delete_tree_confirm' => 'Are you sure you want to delete this tree and all its links?',
        'links_in_tree' => 'Links in This Tree',
        'empty_tree_links' => 'No links in this tree yet',
        'empty_tree_links_desc' => 'Use the button above to add the first link to this tree.',
        'active_status' => 'Active',
        'inactive_status' => 'Off',
        'inactive_label' => '(Inactive)',
        'clicks_count' => '{count} clicks',
        'total_links_count' => '{count} links',
        'total_clicks_count' => '{count} total clicks',
        'create_tree_title' => 'Create New Tree',
        'create_tree_desc' => 'Define a custom URL slug and identity for your new tree.',
        'create_tree_btn' => 'Create New Tree',
        'available_trees' => 'Available Trees',
        'manage_links' => 'Manage Links',
        'see' => 'View',
        'edit_tree_link_title' => 'Edit Linktree Item',
        'tree_not_found' => 'Link Tree Not Found',
        'tree_not_found_desc' => 'The bio link page with the requested URL is not available or has been moved.',
        'go_home' => 'Back to Home',
        'share' => 'Share',
        'scan_qr_desc' => 'Scan the code above with your mobile camera to open this bio link page instantly.',
        'close' => 'Close',
        'url_copied_toast' => 'Linktree URL copied to clipboard!',
        'no_active_links' => 'No active links in this tree yet',
        'check_back_later' => 'Please check back in a few moments.',
        'qr_code_title' => 'Linktree QR Code',
        'footer_text' => '© ' . date('Y') . ' MYP',

        // Reorganized Management UI Tabs & Keys
        'tab_links' => 'Links',
        'tab_profile' => 'Profile & Settings',
        'tab_all_trees' => 'All Trees',
        'btn_add_link' => '+ Add New Link',
        'btn_hide_form' => 'Hide Form',
        'danger_zone' => 'Danger Zone',
        'danger_zone_desc' => 'Permanently delete this tree and all its links.',
        'stats_active_links' => '{count} active links',
        'stats_total_clicks' => '{count} total clicks',
        'btn_back_to_shortener' => 'Shortener',
        'empty_tree_cta' => 'Add First Link',
        'move_up' => 'Move up',
        'move_down' => 'Move down',
        'social_section_title' => 'Social Media & External Links',
        'identity_section_title' => 'Identity & URL Slug',
    ]
];

function __t($key, $replace = []) {
    global $translations, $currentLang;
    $text = $translations[$currentLang][$key] ?? $translations['id'][$key] ?? $key;
    foreach ($replace as $k => $v) {
        $text = str_replace('{' . $k . '}', $v, $text);
    }
    return $text;
}

function getLangToggleUrl($targetLang) {
    $params = $_GET;
    $params['lang'] = $targetLang;
    return '?' . http_build_query($params);
}
