CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  short_code TEXT NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  title TEXT DEFAULT NULL,
  clicks INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_short_code ON links (short_code);

CREATE TABLE IF NOT EXISTS link_trees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  bio TEXT DEFAULT NULL,
  avatar_type TEXT DEFAULT 'initials',
  avatar_value TEXT DEFAULT NULL,
  instagram_url TEXT DEFAULT NULL,
  youtube_url TEXT DEFAULT NULL,
  telegram_url TEXT DEFAULT NULL,
  website_url TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS link_tree_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tree_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT DEFAULT NULL,
  url TEXT NOT NULL,
  icon TEXT DEFAULT 'link',
  badge TEXT DEFAULT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  clicks INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tree_id) REFERENCES link_trees (id) ON DELETE CASCADE
);

